apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-auth.yaml
  - deployment-wallet.yaml
  - deployment-fx.yaml
  - deployment-api-gateway.yaml
  - redis.yaml
  - rabbitmq.yaml
  - ingress.yaml
  - env-secrets.yaml
  - keda-scaledobject-auth.yaml
  - keda-scaledobject-wallet.yaml
  - keda-scaledobject-api-gateway.yaml
  - keda-scaledobject-fx.yaml
  - namespace.yaml

namespace: default
